image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
https://www:
  postman:
    com/postman/workspace/published-postman-templates/documentation/631643-f695cab7-6878-eb55-7943-ad88e1ccfd65?ctx=documentation:

build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации